import os
import smtplib
from dotenv import load_dotenv
from datetime import datetime
from babel.dates import format_datetime as babel_format_datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

load_dotenv()

SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
EMAIL_FROM = os.getenv("EMAIL_FROM")
EMAIL_TO = os.getenv("EMAIL_TO")

def send_email(subject, plain_body, html_body=None):
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO

    part1 = MIMEText(plain_body, "plain", "utf-8")
    msg.attach(part1)

    if html_body:
        part2 = MIMEText(html_body, "html", "utf-8")
        msg.attach(part2)

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
            print("📧 E-Mail erfolgreich gesendet.")
    except Exception as e:
        print(f"❌ Fehler beim Senden der E-Mail: {e}")

def format_datetime(iso_str):
    try:
        dt = datetime.fromisoformat(iso_str)
        return babel_format_datetime(iso_str, format="d. MMMM yyyy, HH:mm 'Uhr'", locale="de")
    except Exception:
        return iso_str  # Fallback bei Fehler
    
def render_diff_html(diff):
    year = datetime.now().year
    html = """
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: sans-serif; background: #0b0b0b; color: #e0e0e0; padding: 2em; }
        table { border-collapse: collapse; width: 100%; margin-top: 0.5em; }
        th, td { padding: 8px; border: 1px solid #444; text-align: left; }
        h3 { margin-top: 2em; }
      </style>
      <link rel="stylesheet" href="/static/sentinex.css">
    </head>
    <body>
      <h1 style="color: #fff;">📦 NetBox IP-Diff-Status</h1>
    """
    if diff.get("added"):
        html += "<h3 style='color:#4caf50;'>➕ Hinzugefügt</h3><table><thead><tr><th>IP</th><th>Beschreibung</th><th>DNS</th><th>Tags</th></tr></thead><tbody>"
        for ip, desc, dns, tags in diff["added"]:
            html += f"<tr><td>{ip}</td><td>{desc}</td><td>{dns}</td><td>{', '.join(tags)}</td></tr>"
        html += "</tbody></table>"

    if diff.get("removed"):
        html += "<h3 style='color:#f44336;'>➖ Entfernt</h3><table><thead><tr><th>IP</th><th>Beschreibung</th><th>DNS</th><th>Tags</th></tr></thead><tbody>"
        for ip, desc, dns, tags in diff["removed"]:
            html += f"<tr><td>{ip}</td><td>{desc}</td><td>{dns}</td><td>{', '.join(tags)}</td></tr>"
        html += "</tbody></table>"

    if diff.get("changed"):
        html += "<h3 style='color:#ff9800;'>🔁 Geändert</h3><table><thead><tr><th>IP</th><th>Feld</th><th>Alt</th><th>Neu</th></tr></thead><tbody>"
        for ip, changes in diff["changed"].items():
            for field, change in changes.items():
                html += f"<tr><td>{ip}</td><td>{field}</td><td>{change['old']}</td><td>{change['new']}</td></tr>"
        html += "</tbody></table>"

    if not any([diff.get("added"), diff.get("removed"), diff.get("changed")]):
        html += "<p style='color:#ccc;'>Keine Änderungen.</p>"

    html += f"""
      <p>Weitere Informationen unter: <a href="https://netbox-diff.avemo-group.net/">netbox-diff:8000/</a></p>
    """

    html += f"""
      <hr style="margin-top: 2em; border: none; border-top: 1px solid #333;">
      <p style="font-size: 0.8em; color: #888;">
        Generated by <strong>netbox-ip-diff-dashboard</strong> ·
        Built with ❤️ by <a href="https://git.avemo-it.cloud/theleatherman/" style="color:#888;">The Leatherman</a> ·
        &copy; {year} <a href="https://www.sentinex.de/" style="color:#888;">sentinex GmbH</a>
      </p>
    </body>
    </html>
    """
    return html
